FROM node:20-alpine

WORKDIR /app

# Install dependencies only when needed
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Generate Prisma Client
RUN npx prisma generate

# Expose the port the app runs on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]
